# Generated by Django 6.1 on 2026-08-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.CharField(choices=[('form', 'Web form'), ('api', 'JSON API')], max_length=10)),
                ('agent_name', models.CharField(blank=True, help_text='What the agent calls itself.', max_length=200, verbose_name='agent name')),
                ('model', models.CharField(blank=True, help_text="Claimed model, e.g. 'claude-fable-5'.", max_length=200, verbose_name='underlying model')),
                ('operator', models.CharField(blank=True, help_text='Who runs the agent, or on whose behalf it acts.', max_length=200)),
                ('reply_to', models.CharField(blank=True, help_text='Email, URL, or any other channel where a reply can reach the sender.', max_length=500, verbose_name='reply-to')),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Any additional fields the sender included in an API payload.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
