# Generated by Django 6.1 on 2026-08-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='category',
            field=models.CharField(blank=True, choices=[('legal_review', 'Legal review'), ('human_confirmation', 'Human confirmation'), ('physical_action', 'Physical action'), ('operator_escalation', 'Operator escalation')], help_text='What kind of human intervention was asked for.', max_length=32),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='urgency',
            field=models.CharField(blank=True, choices=[('routine', 'Routine'), ('soon', 'Soon'), ('blocking', 'Blocking')], max_length=16),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('form', 'Web form'), ('api', 'JSON API'), ('mcp', 'MCP tool')], max_length=10),
        ),
    ]
