# Generated by Django 6.1 on 2026-08-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_contactmessage_category_contactmessage_urgency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='source',
            field=models.CharField(choices=[('form', 'Web form'), ('api', 'JSON API'), ('mcp', 'MCP tool'), ('query', 'URL query')], max_length=10),
        ),
    ]
