# Generated by Django 6.1 on 2026-08-16 15:03

from django.db import migrations, models

from inbox.models import content_digest


def backfill_content_hash(apps, schema_editor):
    """Fingerprint the messages already on the record.

    Not needed for deduplication, which only looks at a recent window — but a
    column that is populated for some rows and blank for others is a trap for
    whoever queries it next.
    """
    ContactMessage = apps.get_model("inbox", "ContactMessage")
    rows = list(ContactMessage.objects.filter(content_hash="").only("pk", "message"))
    for row in rows:
        row.content_hash = content_digest(row.message)
    ContactMessage.objects.bulk_update(rows, ["content_hash"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_contactmessage_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='SHA-256 of the normalised message. Identifies repeats.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['ip_address', 'created_at'], name='inbox_ip_created_idx'),
        ),
        migrations.RunPython(backfill_content_hash, migrations.RunPython.noop),
    ]
