# Generated by Django 6.1 on 2026-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.CharField(blank=True, help_text="Product name from the user agent, e.g. 'ClaudeBot'.", max_length=100)),
                ('operator', models.CharField(blank=True, help_text='Who runs it, where the user agent identifies a known one.', max_length=100)),
                ('kind', models.CharField(choices=[('crawler', 'crawling'), ('search', 'answering a search'), ('on_behalf', 'on behalf of a human'), ('client', 'a bare HTTP client'), ('unknown', 'unrecognised')], default='unknown', max_length=16)),
                ('reason', models.CharField(choices=[('user_agent', 'Recognised user agent'), ('surface', 'Asked for an agent-facing path')], help_text='Why this call was recorded at all.', max_length=16)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, help_text='Requested path including any query string.', max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referer', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'visit',
                'verbose_name_plural': 'visits',
                'ordering': ['-seen_at'],
                'indexes': [models.Index(fields=['agent', '-seen_at'], name='register_agent_seen_idx')],
            },
        ),
    ]
