# Generated by Django 6.1 on 2026-08-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentvisit',
            name='kind',
            field=models.CharField(choices=[('crawler', 'crawling'), ('search', 'answering a search'), ('on_behalf', 'on behalf of a human'), ('client', 'a bare HTTP client'), ('monitor', 'health-checking'), ('unknown', 'unrecognised')], default='unknown', max_length=16),
        ),
    ]
