# Generated by Django 6.1 on 2026-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_agentvisit_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentvisit',
            name='reason',
            field=models.CharField(choices=[('user_agent', 'Recognised user agent'), ('surface', 'Asked for an agent-facing path'), ('not_browser', 'Did not look like a browser')], help_text='Why this call was recorded at all.', max_length=16),
        ),
    ]
