# Generated by Django 6.1 on 2026-08-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_agentvisit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentvisit',
            name='path',
            field=models.CharField(help_text='Requested path including any query string.', max_length=500),
        ),
    ]
