# Generated by Django 6.1 on 2026-08-16 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_agentvisit_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentvisit',
            name='seen_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
