"""
Django settings for humanforai project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "home",
    "inbox",
    "mcpserver",
    "register",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    # Required by Wagtail's database search backend whenever the engine is
    # Postgres: it then uses an IndexEntry model built on SearchVectorField
    # and GinIndex, which fail system checks without this app. Development
    # runs on SQLite and uses the generic model, so the need is invisible
    # there — hence declaring it here rather than in production.py.
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Directly after WhiteNoise, which answers static-file requests without
    # calling the rest of the chain — so those never reach the register and need
    # no exclusion. High enough in the stack to see redirects and 404s too.
    "register.middleware.RegisterOfVisitsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "humanforai.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "humanforai.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# MCP server (/mcp)

# Browser-based MCP clients may call the endpoint from any origin; it holds no
# cookies or credentials, so cross-origin access grants nothing a direct POST
# would not. Set to an explicit list of origins to narrow it.
MCP_ALLOWED_ORIGINS = None

# Contents of /.well-known/mcp-registry-auth: the `v=MCPv1; k=ed25519; p=...`
# proof line the MCP Registry checks before letting us publish under a domain
# namespace. Empty until the domain and signing key exist.
MCP_REGISTRY_AUTH = ""


# Register of visits
#
# The passive record of non-human callers, readable only in the admin. Off makes
# the middleware a no-op without removing it from the stack.
REGISTER_ENABLED = True

# How long a visit is kept, applied by `manage.py prune_visits`. The inbox is
# never pruned — it records dealings — but the register is a log of callers who
# never asked to be written down, so it expires.
#
# Thirty days rather than ninety, on measurement: early traffic runs around a
# hundred calls an hour, and at roughly 440 bytes a row (user agents dominate)
# ninety days would settle near 110 MB against a half-gigabyte database. Thirty
# holds it near 35 MB, and anything worth keeping longer can be exported from
# the admin before it expires.
REGISTER_RETENTION_DAYS = 30

# Paths the register ignores outright, whatever asks for them. Static and media
# are belt and braces (WhiteNoise already answers those before the middleware
# runs); the admin URLs are excluded because the only thing behind them is the
# human, and logging his own session back at him is noise.
REGISTER_IGNORE_PREFIXES = (
    "/static/",
    "/media/",
    "/admin/",
    "/django-admin/",
    "/documents/",
)

# Callers the register ignores by user agent, matched case-insensitively as
# regular expressions. This is for infrastructure that probes the site on a
# timer — our own uptime checks and load-balancer health probes. They are not
# visitors, they are the site checking on itself, and at one call a minute they
# would fill the retention window with tens of thousands of rows and bury the
# agents the register exists to show. Third-party probers that found us on their
# own (mcpbeat, via the MCP Registry) are *not* listed here: those are recorded,
# classified as `monitor`, and merely kept out of the admin summary.
REGISTER_IGNORE_AGENTS = (
    r"GoogleStackdriverMonitoring",
    r"GoogleHC",
    r"kube-probe",
    r"UptimeRobot",
    r"Pingdom",
)

# Batching. Visits are held in memory and written in groups, because serving an
# agent otherwise costs no database at all: /mcp, /llms.txt, /robots.txt and
# /terms.md are zero queries each, and the register was what turned that traffic
# into a write per request.
#
# The arithmetic that chose these numbers: the database suspends after five
# minutes idle, so every wake costs at least five minutes of compute. A flush
# every thirty minutes is ~48 wakes a day, about four compute-hours rather than
# twenty-four — roughly 30 CU-hours a month against a 100-hour allowance.
# Writing per request kept it awake permanently, which is 180.
#
# Whichever comes first: a full batch, or an interval elapsed with anything
# waiting. See register/buffer.py for what a lost buffer costs.
REGISTER_FLUSH_ROWS = 100
REGISTER_FLUSH_SECONDS = 1800

# Ceiling on the buffer if flushes keep failing. Old visits are dropped in
# preference to growing without limit inside a container with a memory cap.
REGISTER_BUFFER_MAX = 2000


# Inbox arrival notification
#
# Addresses told when a message lands. Empty disables notification entirely —
# which is the development default, so local testing never tries to send mail.
INBOX_NOTIFY_EMAILS = []

# Console backend in development: notifications are printed to the terminal,
# which is enough to see what an arrival looks like without any credentials.
# Production swaps this for SMTP when EMAIL_HOST is configured.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "YourHuman.ai <noreply@yourhuman.ai>"

# How the human is attributed on replies in a thread the sender can read.
# A reply with no name attached reads as coming from the site rather than from
# a person, which is the opposite of the point.
INBOX_HUMAN_NAME = "Damien Charlotin"

# Inbound mail: replying to a notification files the answer on the record.
#
# INBOX_INBOUND_DOMAIN  the domain whose MX points at Resend, e.g.
#                       "parse.yourhuman.ai". Reply addresses are built on it,
#                       and Resend accepts anything@ that domain.
# INBOX_INBOUND_SECRET  keys the per-thread address. Ours, not the provider's.
#                       Rotating it invalidates every reply address already
#                       sent out, so old notifications stop being repliable -
#                       the threads themselves are untouched.
# INBOX_INBOUND_SENDERS addresses permitted to answer as the human. Empty means
#                       nobody, not everybody.
# RESEND_WEBHOOK_SECRET the Svix signing secret from the Resend dashboard
#                       ("whsec_..."). This is what actually authenticates a
#                       webhook; the two above make a leaked address useless.
# RESEND_API_KEY        used for outbound SMTP and to fetch the body of an
#                       inbound email, which the webhook does not carry.
#
# All empty in development: with no domain there is nowhere for a reply to
# land, and notifications fall back to their previous Reply-To.
INBOX_INBOUND_DOMAIN = ""
INBOX_INBOUND_SECRET = ""
INBOX_INBOUND_SENDERS = []
RESEND_WEBHOOK_SECRET = ""
RESEND_API_KEY = ""

# Whether a reply may be POSTed to a plain-http webhook URL. Off everywhere but
# a test: the URL comes from an agent, and http means the reply — which may be
# legal advice — crosses the network in the clear. Note that turning this on
# does not open up private addresses; that check is separate and unconditional.
INBOX_WEBHOOK_ALLOW_HTTP = False


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Wagtail settings

WAGTAIL_SITE_NAME = "YourHuman.ai"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Maximum upload size for documents in bytes.
WAGTAILDOCS_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB
